"""Initial migration with tables

Revision ID: 85bd5f928444
Revises: 
Create Date: 2025-03-21 11:04:49.086014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bd5f928444'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garments_id'), 'garments', ['id'], unique=False)
    op.create_table('human_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_models_id'), 'human_models', ['id'], unique=False)
    op.create_table('output_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_model_id', sa.Integer(), nullable=True),
    sa.Column('garment_id', sa.Integer(), nullable=True),
    sa.Column('output_image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.ForeignKeyConstraint(['human_model_id'], ['human_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_images_id'), 'output_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_output_images_id'), table_name='output_images')
    op.drop_table('output_images')
    op.drop_index(op.f('ix_human_models_id'), table_name='human_models')
    op.drop_table('human_models')
    op.drop_index(op.f('ix_garments_id'), table_name='garments')
    op.drop_table('garments')
    # ### end Alembic commands ###
